# **Laboratorio 1: Una introducción a NumPy**



## **1. Funciones en python**

Una función permite definir un bloque de código reutilizable que se puede ejecutar muchas veces dentro del mismo código. Las funciones cuentan con una estructura definida (mostrada a continuación). Es importante mencionar que se debe respetar la indexación en la estructura de las funciones para evitar errores al ejecutarla.

```
def nombre_funcion(parametros_entrada):
    cuerpo(operaciones o procedimiento)
    return (variable de salida o repsuesta)

```


A continuación se muestra un ejemplo de función, la cual, recibe como parámetros 2 números, en el cuerpo de esta función se realiza la operación deseada, en este caso una suma, y se retorna la variable que contiene la respuesta a esta función.

In [ ]:
def suma(a,b):
    respuesta= a+b
    return respuesta


Esta es una manera genérica de realizar operaciones, por lo que se puede utilizar las veces que sea necesario dentro del mismo código.
En las siguientes celdas se observa cómo se utiliza una función para diferentes casos.

In [ ]:
suma(1,4)

5

In [ ]:
suma(100.5,-30)

70.5

Para cada uno de los siguientes problemas de programación, defina una función que los resuelva. No puede utilizar alguna librería de Python con  NumPy o Scipy con métodos preestablecidos para resolverlos. Cada definición de la función deberá probarla con un ejemplo para validar la solución.

**1.1. Escriba una función que reciba como argumento una lista con números y retorne la multiplicación de todos los números dentro de la misma.**

In [1]:
def multiplicar_numeros(lista_numeros):
    resultado = 1  # Iniciar con 1 ya que es el elemento neutro de la multiplicación
    for numero in lista_numeros:
        resultado *= numero  # Multiplicar el resultado por cada número en la lista
    return resultado

In [2]:
lista_ejemplo = [1,3,5]

resultado_multiplicacion = multiplicar_numeros(lista_ejemplo)
print(resultado_multiplicacion)

15


**1.2. Escriba una función que reciba como argumento un numero entero positivo y retorne el factorial del mismo.**

**Nota:** Recuerde que el factorial de un número está dado por la siguiente fórmula:

\begin{align}
        n! = n * (n-1) * (n-2) * (n-3) * ... *(1)
    \end{align}

In [4]:
def factorial(numero):
  if numero == 0:
    return 1 # El factorial de 0 es 1
  resultado = 1

  for i in range(1, numero + 1):
    resultado *= i # Multiplicar el resultado por cada número hasta llegar al número dado
  return resultado

In [6]:
numero_ejemplo = 6
resultado_factorial = factorial(numero_ejemplo)
print(resultado_factorial)

720


**1.3. Escriba una función que reciba como argumento una lista con números y retorne el promedio los números dentro de la misma.**

In [7]:
# Definir la función para calcular el promedio de los números en una lista
def calcular_promedio(lista_numeros):
    if not lista_numeros:  # Verificar si la lista está vacía
        return 0  # Retornar 0 si la lista está vacía para evitar división por cero
    suma_numeros = sum(lista_numeros)  # Sumar todos los números en la lista
    cantidad_numeros = len(lista_numeros)  # Contar la cantidad de números en la lista
    promedio = suma_numeros / cantidad_numeros  # Calcular el promedio
    return promedio

In [8]:
lista_test = [1,4,5,6,7]
resultado_lista_test = calcular_promedio(lista_test)
print(resultado_lista_test)

4.6


## **2. ¿Que es NumPy?**

NumPy es una de las librerías más utilizadas. Esta permite realizar desde operaciones matriciales simples hasta complejas transformadas para el procesamiento de señales. Su utilidad en la programación científica radica en la facilidad que ofrece a la hora de realizar operaciones algebraicas complicadas como diagonalización de matrices, y el cálculo de valores y vectores propios. A continuación se detallará más algunas de las principales y más útiles funciones de esta libreria que serán de utilidad dentro del curso:

En primer lugar, vamos a iniciar instalando y/o importando la libreria numpy en nuestro ambiente.

In [17]:
"""
Nota: El siguiente fragmento de código detecta si NumPy está instalado en su sistema y en caso de no ser así,
procede con la instalación automáticamente.

NO SE DEBE MODIFICAR ESTE FRAGMENTO.


"""

try:
  import numpy as np
  print(f"NumPy versión {np.__version__} se encuentra instalada en su sistema.")

except:
  print("NumPy no encontrado en su sistema\n Instalando NumPy...")

  import os
  os.system("pip install numpy")

  import numpy as np
  print(f"NumPy versión {np.__version__} se encuentra instalada en su sistema.")




NumPy versión 1.25.2 se encuentra instalada en su sistema.


**Nota:** NumPy posee varias funciones que son de utilidad operando listas. A continuación se detallan algunas:

**np.mean:** Devuelve el promedio de un arreglo numérico.

**np.std:** Devuelve la desviación estandar de un arreglo numérico.

**np.sum:** Devuelve la suma de todos los números de un arreglo.

**np.prod:** Devuelve la multiplicación de todos los números de un arreglo.

**np.dot:** Duevuelve el producto punto entre 2 arreglos


De la misma manera, NumPy contiene distintos módulos orientados a un área en específico de las operaciones. Por ejemplo, el módulo *np.math* contiene funciones básicas como factorial, combinatorias, exponencial, etc. Por otra parte, el módulo *np.linalg* contiene funciones para realizar distintas operaciones dentro del campo del álgebra lineal que veremos más adelante.

**2.1. A continuación, repita los puntos 1.1, 1.2 y 1.3 pero utilice NumPy para sus implementaciones.**


In [18]:
#Repetición punto 1.1
# 1.1. Escriba una función que reciba como argumento una lista con números y retorne la multiplicación de todos los números dentro de la misma.

def mult_num(lista1):
  productox = np.prod(lista1)
  return productox

In [19]:
lista2 = [1,5,8,9]
multiplicacion2 = mult_num(lista2)
print(multiplicacion2)

360


In [20]:
#Repetición punto 1.2
# 1.2. Escriba una función que reciba como argumento un numero entero positivo y retorne el factorial del mismo.
import math
def fact_num(arg):
  operacion_factorial = math.factorial(arg)
  return operacion_factorial


In [21]:
arg = 6
resul_arg = fact_num(arg)
print(resul_arg)

720


In [22]:
#Repetición punto 1.3
# 1.3. Escriba una función que reciba como argumento una lista con números y retorne el promedio los números dentro de la misma.

def prom(lista_promedio):
  promediox = np.mean(lista_promedio)
  return promediox

In [23]:
lista_train = [1,2,3,4,5,6,7,8,9,10]
resul_prom = prom(lista_train)
print(resul_prom)

5.5


## **3. Arrays en numpy**

Dentro de NumPy, una de los principales elementos son los *arrays*, una estructura de datos similar a la lista tradicional de Python pero que permite mayor versatilidad a la hora de realizar operaciones. Los arrays son útiles a la hora de representar información como vectores y matrices.

Para iniciar un vector con los números de 1 a 5 se utiliza la instrucción 'np.array()' de la siguiente manera:



In [24]:
vector = np.array([1,2,3,4,5])
print(vector)

[1 2 3 4 5]


De la misma manera, una matriz puede ser iniciada como una lista de listas según el número de dimensiones que se requiere. Por ejemplo, para iniciar una matriz de 2x2 que contenga los números de 1 a 4 se debe realizar lo siguiente:

In [25]:
matriz = np.array([[1,2],[3,4]])
print(matriz)
print(matriz.shape)

[[1 2]
 [3 4]]
(2, 2)


Como se ve en la celda anterior, todos los arrays tienen un atributo denominado *shape*, que le indica al usuario las dimensiones del objeto, o lo que es lo mismo, el número de objetos en un vector o de filas y columnas en una matriz.

Así como los arrays tienen un atributo denominado shape, existen diferentes atributos que dan más información acerca del array. Acá se detallan algunos de los más comunes:

**array.ndim:** Especifica el número de dimensiones de un array. 1 en el caso de un vector, 2 en el caso de una matriz.

**array.size:** Retorna el número de elementos dentro de un array.

**array.T:** Retorna el array transpuesto.

Algunos ejemplos de estos atributos se ven a continuación:

In [26]:
print("Numero de dimensiones en nuestra matriz:", matriz.ndim)
print("Numero de elementos en nuestra matriz:", matriz.size)
print("Matriz transpuesta de nuestra matriz:\n", matriz.T)

Numero de dimensiones en nuestra matriz: 2
Numero de elementos en nuestra matriz: 4
Matriz transpuesta de nuestra matriz:
 [[1 3]
 [2 4]]


**3.1. Indexación de arrays de numpy**


La indexación es conocida como el proceso para obtener el elemento en una determinada posición dentro de un arreglo (array, lista). Para ello se utilizan los paréntesis cuadrados ([]) para indicar la posición de la que se quiere extraer el valor. En NumPy la indexación es similar a la realizada sobre listas con un ligero cambio.

Cuando se tiene un vector cualquier posición puede ser obtenida simplemente indicando el nombre del vector y la posición deseada. Por ejemplo:

In [29]:
vector = np.array([1,2,3,4,5])
print(vector[4])

5


Por otra parte, en el caso de las matrices usualmente se realiza con una doble indexación en el caso de las listas de listas de Python. Esta manera cambia un poco dentro de los arrays, donde se debe indicar dentro de los paréntesis cuadrados las "coordenadas" del elemento que queremos. Se debe tener en cuenta que al igual que en las listas de listas la primer coordenada indica la fila mientras que la segunda coordenada indica la columna. Por ejemplo:

In [33]:
matriz = np.array([[1,2],[3,4]])
print(matriz[0,1])

2


De la misma manera, si se desea obtener varios elementos se puede hacer uso de la indexación con coordenadas en conjunto con el elemento ":" (dos puntos), donde el número a la izquierda indica la posición inicial y el número a la derecha indica la posición final + 1. Por ejemplo:

```
vector[:]  #Devuelve todos los elementos del vector
vector[2:5] #Devuelve los elementos de la segunda a la cuarta posición
vector[:5] #Devuelve los elementos desde la primera hasta la cuarta posición.
vector[2:] #Devuelve los elementos a partir de la segunda posición hasta el final.
vector[::2] #Devuelve los elementos del primero al último con pasos de 2 posiciones.
vector[2:5:2] #Devuelve los elementos de la posición dos a la posición cuatro con pasos de 2.
```

En matrices se realiza la misma operación según las filas y columnas que se quieren. Por ejemplo:

```
matriz[:,:]  #Devuelve todos los elementos de tanto filas como columnas
matriz[2:5,:] #Devuelve los elementos de la segunda a la cuarta fila y todas las columnas
matriz[:,:5] #Devuelve los elementos para todas las filas desde la primera hasta la cuarta columna.
matriz[2:,:] #Devuelve los elementos a partir de la segunda fila para todas las columnas.
matriz[::2,::3] #Devuelve las filas de la primera a la última con pasos de 2 posiciones y de la primera a la última columna con pasos de 3 posiciones.
```





**3.2. Ejercicios**

1. Escriba una función que reciba como argumento una matriz de numpy (array), obtenga todos los elementos de la diagonal de una matriz de NxN y los retorne en un array de NumPy.

In [34]:
import numpy as np

def obtener_diagonal(matriz):
    """
    Esta función recibe una matriz cuadrada de NxN y retorna un array
    de NumPy que contiene los elementos de la diagonal de la matriz.

    Parámetros:
    matriz (np.array): Una matriz cuadrada de NxN.

    Retorna:
    np.array: Un array de NumPy que contiene los elementos de la diagonal.
    """
    # Usando la función np.diag para obtener los elementos de la diagonal
    diagonal = np.diag(matriz)
    return diagonal


In [35]:
# Crear una matriz cuadrada de 3x3 como ejemplo
matriz_ejemplo = np.array([[1, 2, 3],
                           [4, 5, 6],
                           [7, 8, 9]])

# Obtener los elementos de la diagonal
diagonal = obtener_diagonal(matriz_ejemplo)

# Imprimir la diagonal
print(diagonal)


[1 5 9]


2. Escriba una función que reciba como argumentos una matriz de NxN y un número de fila y devuelva todos los elementos de determinada fila.

In [36]:
import numpy as np

def obtener_elementos_fila(matriz, numero_fila):
    """
    Esta función recibe una matriz cuadrada de NxN y un número de fila,
    y retorna un array de NumPy que contiene los elementos de esa fila.

    Parámetros:
    matriz (np.array): Una matriz cuadrada de NxN.
    numero_fila (int): El número de la fila de la que se quieren obtener los elementos.

    Retorna:
    np.array: Un array de NumPy que contiene los elementos de la fila especificada.
    """
    # Asegurarse de que el número de fila esté dentro del rango de la matriz
    if numero_fila >= 0 and numero_fila < matriz.shape[0]:
        # Obtener los elementos de la fila especificada
        fila = matriz[numero_fila, :]
        return fila
    else:
        raise ValueError("El número de fila está fuera del rango de la matriz.")

# Ejemplo de uso
if __name__ == "__main__":
    # Crear una matriz cuadrada de 3x3 como ejemplo
    matriz_ejemplo = np.array([[1, 2, 3],
                               [4, 5, 6],
                               [7, 8, 9]])

    # Especificar el número de fila que queremos obtener
    numero_fila = 1  # Esto devolverá la segunda fila, ya que la indexación comienza en 0

    # Obtener los elementos de la fila especificada
    fila = obtener_elementos_fila(matriz_ejemplo, numero_fila)

    # Imprimir los elementos de la fila
    print(fila)


[4 5 6]


3. Escriba una función que reciba como argumentos una matriz de NxN y un número de columna y devuelva todos los elementos de determinada columna.

In [38]:
import numpy as np

def obtener_elementos_columna(matriz, numero_col):
    """
    Esta función recibe una matriz cuadrada de NxN y un número de fila,
    y retorna un array de NumPy que contiene los elementos de esa fila.

    Parámetros:
    matriz (np.array): Una matriz cuadrada de NxN.
    numero_fila (int): El número de la fila de la que se quieren obtener los elementos.

    Retorna:
    np.array: Un array de NumPy que contiene los elementos de la fila especificada.
    """
    # Asegurarse de que el número de fila esté dentro del rango de la matriz
    if numero_col >= 0 and numero_col < matriz.shape[0]:
        # Obtener los elementos de la fila especificada
        col = matriz[:, numero_col]
        return col
    else:
        raise ValueError("El número de columna está fuera del rango de la matriz.")

# Ejemplo de uso
if __name__ == "__main__":
    # Crear una matriz cuadrada de 3x3 como ejemplo
    matriz_ejemplo = np.array([[1, 2, 3],
                               [4, 5, 6],
                               [7, 8, 9]])

    # Especificar el número de fila que queremos obtener
    numero_col = 1  # Esto devolverá la segunda fila, ya que la indexación comienza en 0

    # Obtener los elementos de la fila especificada
    col = obtener_elementos_columna(matriz_ejemplo, numero_col)

    # Imprimir los elementos de la fila
    print(col)

[2 5 8]


4. Escriba una función que reciba como argumento una matriz y retorne su transpuesta.

In [39]:
import numpy as np

def matriz_transpuesta(matriz):
  transpuesta = np.transpose(matriz)
  return transpuesta

In [40]:
matrix = np.array([[1,7,8],[4,9,2],[4,3,1]])
matrix_transpuesta = matriz_transpuesta(matrix)
print(matrix_transpuesta)

[[1 4 4]
 [7 9 3]
 [8 2 1]]


**3.3. Tipos especiales de matrices en NumPy**

De igual manera, se pueden crear ciertos tipos de matriz especiales utilizando NumPy mediante el uso del argumento shape visto anteriormente. Algunas matrices pueden ser:

**Matriz donde todos sus elementos son 0:** Esta matriz puede ser creada utilizando la función *np.zeros()* donde como argumento *shape* se debe indicar las dimensiones con las que se quiere construir la matriz.

**Matriz donde todos sus elementos son 1:** Esta matriz puede ser creada utilizando la función *np.ones()* donde como argumento *shape* se debe indicar las dimensiones con las que se quiere construir la matriz.

**Matriz identidad:** Esta matriz puede ser creada utilizando la función *np.eye* donde como argumento obligatorio se debe indicar N, el número de filas, y como argumento opcional se puede indicar M (número de columnas) y/o k (posición de la diagonal, donde 0 indica la diagonal principal, un número positivo indica una diagonal superior y un número negativo indica una diagonal inferior).

**3.4. Ejercicios**

1. Cree un vector de 20 elementos donde todos sus elementos son el número 1 e imprima sus dimensiones.


In [43]:
vector_veinte = np.array([1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1])

In [47]:
dimension_vector_veinte = vector_veinte.ndim
print(dimension_vector_veinte)

1



2. Cree una matriz de 5 filas por 4 columnas donde todos sus elementos sean el número 0.


In [52]:
import numpy as np

matriz_cero = np.ones(20)

matriz_cero_dim = matriz_cero.shape

matriz_cero_dim

(20,)


3. Cree una matriz de 5x5 donde todos los elementos de la diagonal principal son el número 1 y los demás son el número 0.



In [53]:
import numpy as np

matriz_diag_uno = np.eye(5)

matriz_diag_uno

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

4. Cree una función que reciba como argumento una matriz y retorne la suma por filas de sus elementos.

    **Hint:** ¿Que función tiene el parámetro axis dentro de la función np.sum()?

In [56]:
import numpy as np

def suma_por_filas(matriz):
    """
    Esta función recibe una matriz y retorna la suma por filas de sus elementos.

    Parámetros:
    matriz (np.array): Una matriz de cualquier tamaño.

    Retorna:
    np.array: Un array de NumPy que contiene la suma de los elementos por filas.
    """
    # Usar np.sum() con axis=1 para sumar los elementos por fila
    suma_fila = np.sum(matriz, axis=1)
    return suma_fila

# Ejemplo de uso
if __name__ == "__main__":
    matriz_ejemplo3 = np.array([[1, 2, 3],
                               [4, 5, 6],
                               [7, 8, 9]])

    # Llamar a la función y obtener la suma por filas
    resultado = suma_por_filas(matriz_ejemplo3)

    # Imprimir el resultado
    print(resultado)

[ 6 15 24]


5. Cree una función que reciba como argumento una matriz y retorne la suma por columnas de sus elementos.

    **Hint:** ¿Que función tiene el parámetro axis dentro de la función np.sum()?

In [57]:
import numpy as np

def suma_por_columnas(matriz):
    """
    Esta función recibe una matriz y retorna la suma por columnas de sus elementos.

    Parámetros:
    matriz (np.array): Una matriz de cualquier tamaño.

    Retorna:
    np.array: Un array de NumPy que contiene la suma de los elementos por columnas.
    """
    # Usar np.sum() con axis=0 para sumar los elementos por columna
    suma_columna = np.sum(matriz, axis=0)
    return suma_columna

# Ejemplo de uso
if __name__ == "__main__":
    matriz_ejemplo = np.array([[1, 2, 3],
                               [4, 5, 6],
                               [7, 8, 9]])

    # Llamar a la función y obtener la suma por columnas
    resultado = suma_por_columnas(matriz_ejemplo)

    # Imprimir el resultado
    print(resultado)

[12 15 18]
