# **Laboratorio 2: Operaciones con Matrices**


## **1. Propiedades y operaciones con matrices**

NumPy permite realizar distintas operaciones con matrices, entre las principales se encuentran:

```
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
```
- **Suma de matrices**: La suma de matrices elemento a elemento se realiza sumando las dos matrices como dos variables estandar.
```
c = a + b
[[ 6  8]
 [10 12]]
```
- **Resta de matrices**: La resta de matrices elemento a elemento se realiza restando las dos matrices como dos variables estandar.
```
c = a - b
[[-4 -4]
 [-4 -4]]
```
- **División de matrices**: La división de matrices elemento a elemento se realiza dividiendo las dos matrices como dos variables estandar (esto también incluye la división entera y la operación módulo).
```
c = a / b
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
```

- **Multiplicación de matrices (elemento a elemento)**: La multiplicación de matrices elemento a elemento se realiza multiplicando las dos matrices como dos variables estandar.
```
c = a * b
[[ 5 12]
 [21 32]]
```

- **Producto matricial**: El producto entre matrices se puede realizar de varias formas, algunas de ellas incluyen el símbolo '@' como operador o el uso de la función *numpy.dot()*.
```
c = a @ b
[[19 22]
 [43 50]]
c = np.dot(a,b)
[[19 22]
 [43 50]]
```






**1.1. Ejercicios**

Para las siguientes parejas de matrices determine:

- Suma de las matrices elemento a elemento.

- Resta de las matrices elemento a elemento.

- División de las matrices elemento a elemento.

- Multiplicación de las matrices elemento a elemento.

- Producto matricial.

**Pareja 1:**

\begin{align}
 \begin{pmatrix}
 11 & 3 & 8 & \\
 2 & 16 & 6 & \\
 8 & 6 & 0 & \\
\end{pmatrix}  
 \begin{pmatrix}
 9 & 16 & 5 & \\
 11 & 10 & 12 & \\
 4 & 16 & 6 & \\
\end{pmatrix}
\end{align}


In [ ]:
#Suma de las matrices

import numpy as np
a = np.array([[11,3,8],[2,16,6],[8,6,0]])
b = np.array([[9,16,5],[11,10,12],[4,16,6]])

c = a + b
print(c)

[[20 19 13]
 [13 26 18]
 [12 22  6]]


In [ ]:
#Resta de las matrices

import numpy as np
a = np.array([[11,3,8],[2,16,6],[8,6,0]])
b = np.array([[9,16,5],[11,10,12],[4,16,6]])

d = a - b
print(d)

[[  2 -13   3]
 [ -9   6  -6]
 [  4 -10  -6]]


In [ ]:
#División de las matrices

import numpy as np
a = np.array([[11,3,8],[2,16,6],[8,6,0]])
b = np.array([[9,16,5],[11,10,12],[4,16,6]])

e = a / b
print(e)

[[1.22222222 0.1875     1.6       ]
 [0.18181818 1.6        0.5       ]
 [2.         0.375      0.        ]]


In [ ]:
#Multiplicación de las matrices

import numpy as np
a = np.array([[11,3,8],[2,16,6],[8,6,0]])
b = np.array([[9,16,5],[11,10,12],[4,16,6]])

f = a * b
print(f)

[[ 99  48  40]
 [ 22 160  72]
 [ 32  96   0]]


In [ ]:
#Producto matricial

import numpy as np
a = np.array([[11,3,8],[2,16,6],[8,6,0]])
b = np.array([[9,16,5],[11,10,12],[4,16,6]])

g = np.dot(a,b)
print(g)

[[164 334 139]
 [218 288 238]
 [138 188 112]]



**Pareja 2:**

\begin{align}
 \begin{pmatrix}
 18 & 3 & 13 & \\
 6 & 11 & 17 & \\
 8 & 14 & 11 & \\
\end{pmatrix}
 \begin{pmatrix}
 10 & 12 & 13 & \\
 15 & 7 & 4 & \\
 16 & 14 & 7 & \\
\end{pmatrix}
\end{align}

In [ ]:
#Suma de las matrices

In [ ]:
#Resta de las matrices

In [ ]:
#División de las matrices

In [ ]:
#Multiplicación de las matrices

In [ ]:
#Producto matricial

## **2. Operaciones de álgebra lineal**

Numpy permite realizar ciertas operaciones de álgebra lineal haciendo uso de su paquete linalg, hoy observaremos algunas de las principales operaciones que pueden ser realizadas con NumPy.

**np.linalg.det:** Calcula el determinante de un array que debe ser de MxM.

**np.linalg.inv:** Calcula la inversa de un array que debe ser de MxM y retorna un error si la conversión falla o el array no tiene MxM elementos.

**np.linalg.norm:** Calcula la norma vectorial de un array. A partir de esta operación se pueden hallar valores como la distancia Euclidiana.

**np.linalg.eig:** Calcula los eigenvalores y eigenvectores de un array que debe ser de MxM y los retorna en la forma (W,v) donde W es un array que contiene los eigenvalores y v un array que contiene los eigenvectores.

**2.1. Ejercicios**

1. Para cada una de las siguientes matrices:

    a. Determine el número de dimensiones de la matriz.

    b. Determine las dimensiones de la matriz.

    c. Calcule el determinante de la matriz.

    d. Calcule la inversa de la matriz.  

    e. Calcular la distancia euclidiana entre los arrays de las dos últimas filas de cada matriz    

    f. Calcule los valores y vectores propios, e imprímalos en pantalla de la siguiente manera.

  Eigenvalor 1: valor, Eigenvector 1: $[1,2...]$


Matriz 1

\begin{align}
 \begin{pmatrix}
 2 & 9 & 6 \\
 5 & 4 & 3 \\
 9 & 2 & 3 \\
\end{pmatrix}
 \end{align}


Matriz 2

\begin{align}
 \begin{pmatrix}
 9 & 5 & 6 \\
 0 & 9 & 6 \\
 5 & 7 & 3 \\
\end{pmatrix}
 \end{align}


Matriz 3

\begin{align}
 \begin{pmatrix}
 9 & 7 & 2 \\
 3 & 3 & 8 \\
 4 & 8 & 5 \\
\end{pmatrix}
 \end{align}

## **3. Arange vs linspace**

Otros dos métodos conocidos para la creación de arrays son np.arange y np.linspace. Estos métodos son usados especialmente cuando se busca crear arrays que representen una secuencia temporal, como por ejemplo un array representando la variable del tiempo que va de 0 a 50 segundos con pasos de 1 segundo. Ambos métodos reciben como argumentos obligatorios el número de inicio y el número de fin. La principal diferencia entre estos métodos se da en que np.arange recibe como tercer argumento los intervalos para los que se quiere la muestra. Por ejemplo, si se quiere crear un array de 0 a 50 con pasos de 1, la síntesis del código debería ser:

```
array = np.arange(0,51,1)
```
Por otra parte, linspace recibe como tercer argumento el número de muestras que se quiere en el array. Es decir, si se quiere que el array sea de 1 a 50 con pasos de 1 (50 muestras) la síntesis del código debería ser:



```
array = np.linspace(0,50,51)
```

**Nota:** Es importante diferenciar el tipo de dato que contiene el array, ya que en el caso del ejemplo de arange, como se están utilizando pasos enteros (de 1 en 1) el retorno es un array con números en tipo int32, mientras que en el caso del ejemplo de linspace el retorno se da en float64. Comúnmente se trabaja con float64 en NumPy, así que si quisieramos que el retorno del ejemplo de arange sea en formato float64 basta con cambiar el número de pasos a uno que no sea entero o a definir con un punto al final cada número como a continuación:


```
array = np.arange(0., 51., 1)
```




**3.1. Ejercicios**

1. Defina un array que contenga números de 5 a 10 con pasos de 0.25 e imprima su longitud.


In [1]:
import numpy as np

# Definir un array que contenga números de 5 a 10 con pasos de 0.25
array = np.arange(5, 10.25, 0.25)

# Imprimir la longitud del array
longitud = len(array)
longitud

21


2. Defina un array que contenga números de 10 a 20 y que contenga 100 elementos.


In [2]:
# Crear un array que contenga números del 10 al 20 y tenga 100 elementos
import numpy as np

# Usaremos np.linspace para generar 100 valores entre 10 y 20, ambos incluidos
array_numeros = np.linspace(10, 20, 100)

array_numeros

array([10.        , 10.1010101 , 10.2020202 , 10.3030303 , 10.4040404 ,
       10.50505051, 10.60606061, 10.70707071, 10.80808081, 10.90909091,
       11.01010101, 11.11111111, 11.21212121, 11.31313131, 11.41414141,
       11.51515152, 11.61616162, 11.71717172, 11.81818182, 11.91919192,
       12.02020202, 12.12121212, 12.22222222, 12.32323232, 12.42424242,
       12.52525253, 12.62626263, 12.72727273, 12.82828283, 12.92929293,
       13.03030303, 13.13131313, 13.23232323, 13.33333333, 13.43434343,
       13.53535354, 13.63636364, 13.73737374, 13.83838384, 13.93939394,
       14.04040404, 14.14141414, 14.24242424, 14.34343434, 14.44444444,
       14.54545455, 14.64646465, 14.74747475, 14.84848485, 14.94949495,
       15.05050505, 15.15151515, 15.25252525, 15.35353535, 15.45454545,
       15.55555556, 15.65656566, 15.75757576, 15.85858586, 15.95959596,
       16.06060606, 16.16161616, 16.26262626, 16.36363636, 16.46464646,
       16.56565657, 16.66666667, 16.76767677, 16.86868687, 16.96


3. Defina dos arrays con los límites de su preferencia (deben ser los mismos para ambos arrays) utilizando los dos métodos de tal manera que ambos arrays tengan el mismo número de datos e imprima su longitud.

In [4]:
# Definiremos dos arrays con los mismos límites pero utilizando dos métodos diferentes para generarlos.
# Luego, imprimiremos la longitud de cada uno para verificar que tienen el mismo número de datos.

# Método 1: np.linspace para generar un array con valores entre 5 y 15, incluidos, con 50 elementos
array_linspace = np.linspace(5, 15, 50)

# Imprimir la longitud de cada array para confirmar que ambos tienen el mismo número de datos
len_linspace = len(array_linspace)
len_arange = len(array_arange)

len_linspace, len_arange

(50, 50)